PARAMETERS lcTipo, lcDocumentoID
#INCLUDE DOBRA.H

lcTipo = STRTRAN(lcTipo,'*')

DO CASE
	CASE lcTipo = IDDOC_PRD_COSTOS_INDIRECTOS
		DO FORM PRD_DOCUMENT_COSTOS_INDIRECTOS WITH lcDocumentoID

	CASE lcTipo = IDDOC_PRD_JORNALES
		DO FORM PRD_DOCUMENT_JORNALES WITH lcDocumentoID	

	CASE lcTipo = IDDOC_PRD_LIQUIDACIONES
		DO FORM PRD_DOCUMENT_LIQUIDACIONES WITH lcDocumentoID

	CASE lcTipo = IDDOC_PRD_INGRESOS
		DO FORM PRD_DOCUMENT_REINTEGRO_MATERIALES WITH lcDocumentoID	

	CASE lcTipo = IDDOC_PRD_EGRESOS
		DO FORM PRD_DOCUMENT_USO_MATERIALES WITH lcDocumentoID	

	OTHERWISE
		MESSAGEBOX("Lo siento, pero no se puede presentar el documento.")		
ENDCASE