PARAMETERS lcTipo, lcDocumentoID
#INCLUDE DOBRA.H

lcTipo = STRTRAN(lcTipo,'*')
DO CASE
	CASE lcTipo = IDDOC_BAN_DEBITO
		DO FORM BAN_DOCUMENT_DEBITO WITH lcDocumentoID

	CASE lcTipo = IDDOC_BAN_CREDITO
		DO FORM BAN_DOCUMENT_CREDITO WITH lcDocumentoID	

	CASE lcTipo = IDDOC_BAN_TRANSFERENCIA
		DO FORM BAN_DOCUMENT_TRANSFERENCIAS WITH lcDocumentoID	

	CASE lcTipo = IDDOC_BAN_DEPOSITO
		DO FORM BAN_DOCUMENT_DEPOSITO WITH lcDocumentoID	

	CASE lcTipo = IDDOC_BAN_INGRESO
		DO FORM BAN_DOCUMENT_INGRESOS WITH lcDocumentoID

	CASE lcTipo = IDDOC_BAN_EGRESO
		DO FORM BAN_DOCUMENT_EGRESOS WITH lcDocumentoID	

	OTHERWISE
		MESSAGEBOX("Lo siento, pero no se puede presentar el documento.")		
ENDCASE