*SELECT * FROM ACC_ASIENTOS_LICEO ;
*WHERE Fecha >= CTOD("01/01/2001") OR ID = "0000000001" ;
*INTO CURSOR SQLASIENTOS ORDER BY ID

*SELECT SQLASIENTOS
*SCAN ALL
*	SCATTER MEMVAR
*	m.ID = SQLASIENTOS.ID
*	INSERT INTO ACC_ASIENTOS_CENTRO FROM MEMVAR
*ENDSCAN

*SELECT * FROM ACC_CUENTAS_LICEO ;
*INTO CURSOR SQLCUENTAS ORDER BY ID

*SELECT SQLCUENTAS
*SCAN ALL
*	SCATTER MEMVAR
*	m.ID = SQLCUENTAS.ID
*	INSERT INTO ACC_CUENTAS FROM MEMVAR
*ENDSCAN

*SELECT * FROM ACC_ASIENTOS_DT_LICEO ;
*WHERE ASIENTOID IN (SELECT ID FROM ACC_ASIENTOS_CENTRO) ;
*INTO CURSOR SQLDT order by asientoid

*SELECT SQLDT
*SCAN ALL
*	SCATTER MEMVAR
*	m.AsientoID = SQLDT.AsientoID
*	INSERT INTO ACC_ASIENTOS_DT_CENTRO FROM MEMVAR
*ENDSCAN 

* SEG_GRUPOS
*SELECT * FROM SEG_GRUPOS_LICEO ;
*INTO CURSOR SQLGR order by id

*SELECT SQLGR
*SCAN ALL
*	SCATTER MEMVAR
*	INSERT INTO SEG_GRUPOS FROM MEMVAR
*ENDSCAN 

*SEG_USUARIOS
*SELECT * FROM SEG_USUARIOS_LICEO ;
*WHERE ID != "0000000001" ;
*INTO CURSOR SQLUS order by id

*SELECT SQLUS
*SCAN ALL
*	SCATTER MEMVAR
*	INSERT INTO SEG_USUARIOS FROM MEMVAR
*ENDSCAN 

*SEG_RECURSOS
*SELECT * FROM SEG_RECURSOS_LICEO ;
*INTO CURSOR SQLRE order by id

*SELECT SQLRE
*SCAN ALL
*	SCATTER MEMVAR
*	INSERT INTO SEG_RECURSOS FROM MEMVAR
*ENDSCAN 

*SEG_PERFILES
*SELECT * FROM SEG_PERFILES_LICEO ;
*INTO CURSOR SQLPE order by id

*SELECT SQLPE
*SCAN ALL
*	SCATTER MEMVAR
*	INSERT INTO SEG_PERFILES FROM MEMVAR
*ENDSCAN 

*PARAMETROS
SELECT * FROM SIS_PARAMETROS_LICEO ;
INTO CURSOR SQLPA order by id

SELECT SQLPA
SCAN ALL
	SCATTER MEMVAR
	INSERT INTO SIS_PARAMETROS FROM MEMVAR
ENDSCAN 
